import type { AdData } from "@/types";
import { subDays, format } from "date-fns";

function dateStr(d: Date) {
  return format(d, "yyyy-MM-dd");
}

const today = new Date();
const start30 = dateStr(subDays(today, 30));
const end = dateStr(today);

const chivasAds: AdData[] = [
  {
    id: "mock-chivas-1",
    campaignName: "Chivas 2024 | AWA | Brand Awareness | Meta",
    adsetName: "25–44 Whisky Enthusiasts | UK & IE",
    adName: "Chivas_Hero_15s_v1",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 1_240_000,
      reach: 420_000,
      frequency: 2.95,
      spend: 8_400,
      clicks: 9_300,
      ctr: 0.0075,
      cpm: 6.77,
      videoViews: 372_000,
      videoViewRate: 0.3,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-chivas-2",
    campaignName: "Chivas 2024 | AWA | Brand Awareness | Meta",
    adsetName: "25–44 Whisky Enthusiasts | UK & IE",
    adName: "Chivas_Lifestyle_30s_v2",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 890_000,
      reach: 310_000,
      frequency: 2.87,
      spend: 6_200,
      clicks: 5_340,
      ctr: 0.006,
      cpm: 6.97,
      videoViews: 284_800,
      videoViewRate: 0.32,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-chivas-3",
    campaignName: "Chivas 2024 | AWA | Retargeting",
    adsetName: "Site Visitors 30d",
    adName: "Chivas_Retarget_Static_v1",
    channel: "meta",
    objective: "conversion",
    metrics: {
      impressions: 340_000,
      reach: 95_000,
      frequency: 3.58,
      spend: 4_100,
      clicks: 6_800,
      ctr: 0.02,
      cpm: 12.06,
      cpc: 0.6,
      roas: 3.4,
      costPerResult: 48,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-chivas-4",
    campaignName: "Chivas 2024 | AWA | Brand Awareness | Meta",
    adsetName: "Lookalike 1% Purchasers | UK",
    adName: "Chivas_Gifting_Square_v3",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 650_000,
      reach: 230_000,
      frequency: 2.83,
      spend: 5_100,
      clicks: 3_900,
      ctr: 0.006,
      cpm: 7.85,
      videoViews: 195_000,
      videoViewRate: 0.3,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-chivas-5",
    campaignName: "Chivas 2024 | AWA | Brand Awareness | Meta",
    adsetName: "Broad 30–55 | Spirits Interest",
    adName: "Chivas_XV_Feature_v1",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 1_100_000,
      reach: 380_000,
      frequency: 2.89,
      spend: 7_700,
      clicks: 7_700,
      ctr: 0.007,
      cpm: 7.0,
      videoViews: 341_000,
      videoViewRate: 0.31,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
];

const absolutAds: AdData[] = [
  {
    id: "mock-absolut-1",
    campaignName: "Absolut | AWA | Always On | Meta",
    adsetName: "18–34 | Cocktail Culture | EU",
    adName: "Absolut_Rainbow_15s_v1",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 2_100_000,
      reach: 710_000,
      frequency: 2.96,
      spend: 14_700,
      clicks: 21_000,
      ctr: 0.01,
      cpm: 7.0,
      videoViews: 693_000,
      videoViewRate: 0.33,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-absolut-2",
    campaignName: "Absolut | AWA | Always On | Meta",
    adsetName: "18–34 | Cocktail Culture | EU",
    adName: "Absolut_Unique_Campaign_v2",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 1_450_000,
      reach: 510_000,
      frequency: 2.84,
      spend: 10_150,
      clicks: 14_500,
      ctr: 0.01,
      cpm: 7.0,
      videoViews: 478_500,
      videoViewRate: 0.33,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-absolut-3",
    campaignName: "Absolut | CONV | E-Commerce | Meta",
    adsetName: "Purchase Intent | 25–40",
    adName: "Absolut_Ecomm_Carousel_v1",
    channel: "meta",
    objective: "conversion",
    metrics: {
      impressions: 520_000,
      reach: 185_000,
      frequency: 2.81,
      spend: 7_280,
      clicks: 13_000,
      ctr: 0.025,
      cpm: 14.0,
      cpc: 0.56,
      roas: 4.1,
      costPerResult: 52,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-absolut-4",
    campaignName: "Absolut | AWA | Always On | Meta",
    adsetName: "Broad 21–45 | Spirits & Cocktails",
    adName: "Absolut_Vodka_Story_v4",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 980_000,
      reach: 350_000,
      frequency: 2.8,
      spend: 6_860,
      clicks: 9_800,
      ctr: 0.01,
      cpm: 7.0,
      videoViews: 323_400,
      videoViewRate: 0.33,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
];

const jamesonAds: AdData[] = [
  {
    id: "mock-jameson-1",
    campaignName: "Jameson | CONV | St Patrick | Meta",
    adsetName: "21–40 | Irish Whiskey | US",
    adName: "Jameson_SPD_Hero_v1",
    channel: "meta",
    objective: "conversion",
    metrics: {
      impressions: 1_800_000,
      reach: 620_000,
      frequency: 2.9,
      spend: 18_000,
      clicks: 36_000,
      ctr: 0.02,
      cpm: 10.0,
      cpc: 0.5,
      roas: 3.8,
      costPerResult: 42,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-jameson-2",
    campaignName: "Jameson | CONV | Always On | Meta",
    adsetName: "Lookalike 2% Buyers | US",
    adName: "Jameson_Serve_15s_v2",
    channel: "meta",
    objective: "conversion",
    metrics: {
      impressions: 1_100_000,
      reach: 390_000,
      frequency: 2.82,
      spend: 11_000,
      clicks: 24_200,
      ctr: 0.022,
      cpm: 10.0,
      cpc: 0.45,
      roas: 4.2,
      costPerResult: 38,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-jameson-3",
    campaignName: "Jameson | AWA | Brand | Meta",
    adsetName: "Broad 21–45 | Whiskey & Cocktails",
    adName: "Jameson_Brand_Story_v1",
    channel: "meta",
    objective: "awareness",
    metrics: {
      impressions: 870_000,
      reach: 305_000,
      frequency: 2.85,
      spend: 6_090,
      clicks: 6_090,
      ctr: 0.007,
      cpm: 7.0,
      videoViews: 278_400,
      videoViewRate: 0.32,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-jameson-4",
    campaignName: "Jameson | CONV | Retarget | Meta",
    adsetName: "Website Visitors 14d",
    adName: "Jameson_Retarget_Static_v1",
    channel: "meta",
    objective: "conversion",
    metrics: {
      impressions: 290_000,
      reach: 78_000,
      frequency: 3.72,
      spend: 5_510,
      clicks: 8_120,
      ctr: 0.028,
      cpm: 19.0,
      cpc: 0.68,
      roas: 3.1,
      costPerResult: 65,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
  {
    id: "mock-jameson-5",
    campaignName: "Jameson | CONV | Always On | Meta",
    adsetName: "Interest: Whiskey & Bourbon | 25–45",
    adName: "Jameson_Triple_Distilled_v3",
    channel: "meta",
    objective: "conversion",
    metrics: {
      impressions: 760_000,
      reach: 265_000,
      frequency: 2.87,
      spend: 7_600,
      clicks: 15_200,
      ctr: 0.02,
      cpm: 10.0,
      cpc: 0.5,
      roas: 3.5,
      costPerResult: 48,
    },
    thumbnailUrl: undefined,
    dateRange: { start: start30, end },
  },
];

export const mockData: Record<string, AdData[]> = {
  chivas: chivasAds,
  absolut: absolutAds,
  jameson: jamesonAds,
};

export function getMockData(brand: string): AdData[] {
  return mockData[brand] ?? [];
}
